from tkinter import *
from tkinter import ttk
from tkinter import filedialog as fd
from Settings_dialog import *
import pandas as pd
import numpy as np
import os

class Header:
  def __init__(self, Last_Frame, File_Path, File_Name_Csv, File_Name_Png):
    self.Last_Frame = Last_Frame
    self.File_path = File_Path # Equivalent to "header.FilePattern" in Flavio's code
    self.File_Name_Csv = File_Name_Csv
    self.File_Name_Png = File_Name_Png


create_Settings_dialog()

root = Tk()
FileName = fd.askopenfiles(title="Select the CSV and PNG files generated by the BONSAI software",filetypes=[("png and csv files","*")])
data = [None] * (len(FileName)) # Initialize the data struct with the number of files loaded 
File_Header = Header([None]*len(FileName),[None]*len(FileName),[None]*len(FileName),[None]*len(FileName)) # Initialize the attributes of header with the number of files loaded 

# Loop through all files and convert the table data into a DataFrame (Basically a Pandas Table)
for file in range(0, len(FileName)): 
  if FileName[file].name.endswith(".csv"):
    data[file] = pd.read_csv(FileName[file].buffer, header=None, delimiter=",", dtype={"0": np.float32, "1": np.float32, "2": np.intc, "3": np.intc, "4": np.intc, "5": np.intc, "6": np.intc})
    File_Header.File_Name_Csv[file] = os.path.basename(FileName[file].name)
  elif FileName[file].name.endswith(".png"):
    File_Header.File_Name_Png[file] = os.path.basename(FileName[file].name)

# Cleanup the empty values in the srtuct attributes
File_Header.File_path = list(filter(None, File_Header.File_path))
File_Header.File_Name_Csv = list(filter(None, File_Header.File_Name_Csv))
File_Header.File_Name_Png = list(filter(None, File_Header.File_Name_Png))
File_Header.Last_Frame = list(filter(None, File_Header.Last_Frame))


#TODO #6 Import and organize files based on extension
#TODO #7 Create an imput dialog that defines "Figure Organization"
#TODO #9 Separate the dialog creation from the main file to clean up the space a little