from email import header
from tkinter import *
from tkinter import ttk
from tkinter import filedialog as fd
from Settings_dialog import *
import pandas as pd
import numpy as np

class Header:
  def __init__(self, Last_Frame, File_Info, File_Name_Csv, File_Name_Png):
    self.Last_Frame = Last_Frame
    self.File_Info = File_Info
    self.File_Name_Csv = File_Name_Csv
    self.File_Name_Png = File_Name_Png


create_Settings_dialog()

root = Tk()
FileName = fd.askopenfiles(title="Select the CSV and PNG files generated by the BONSAI software",filetypes=[("png and csv files","*")])
data = [None] * (len(FileName))

  for files in range(0, len(FileName)):
    data[files] = pd.read_csv(FileName[files].buffer, header=None, delimiter=",", dtype={"0": np.float32, "1": np.float32, "2": np.intc, "3": np.intc, "4": np.intc, "5": np.intc, "6": np.intc})
    pass


#TODO #6 Import and organize files based on extension
#TODO #7 Create an imput dialog that defines "Figure Organization"
#TODO #9 Separate the dialog creation from the main file to clean up the space a little